lib/stock_exchange_web/router.ex
defmodule StockExchangeWeb.Router do
  use StockExchangeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {StockExchangeWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StockExchangeWeb do
    pipe_through :browser

    get "/", PageController, :index

    # live Routes
    live "/users", UserLive.Index, :index
    live "/users/new", UserLive.Index, :new
    live "/users/:id/edit", UserLive.Index, :edit

    live "/users/:id", UserLive.Show, :show
    live "/users/:id/show/edit", UserLive.Show, :edit
    live "/incoming-stock/simulation", Simulation.IncomingStock
    live "/outgoing-stock/simulation", Simulation.OutgoingStock

    get "/favourite-stocks/:user_id", StockController, :show
    get "/featured-stocks", StockController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", StockExchangeWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: StockExchangeWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/stock_exchange_web/live/live_helpers.ex
defmodule StockExchangeWeb.LiveHelpers do
  import Phoenix.LiveView
  import Phoenix.LiveView.Helpers

  alias Phoenix.LiveView.JS

  @doc """
  Renders a live component inside a modal.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <.modal return_to={Routes.user_index_path(@socket, :index)}>
        <.live_component
          module={StockExchangeWeb.UserLive.FormComponent}
          id={@user.id || :new}
          title={@page_title}
          action={@live_action}
          return_to={Routes.user_index_path(@socket, :index)}
          user: @user
        />
      </.modal>
  """
  def modal(assigns) do
    assigns = assign_new(assigns, :return_to, fn -> nil end)

    ~H"""
    <div id="modal" class="phx-modal fade-in" phx-remove={hide_modal()}>
      <div
        id="modal-content"
        class="phx-modal-content fade-in-scale"
        phx-click-away={JS.dispatch("click", to: "#close")}
        phx-window-keydown={JS.dispatch("click", to: "#close")}
        phx-key="escape"
      >
        <%= if @return_to do %>
          <%= live_patch "✖",
            to: @return_to,
            id: "close",
            class: "phx-modal-close",
            phx_click: hide_modal()
          %>
        <% else %>
          <a id="close" href="#" class="phx-modal-close" phx-click={hide_modal()}>✖</a>
        <% end %>

        <%= render_slot(@inner_block) %>
      </div>
    </div>
    """
  end

  defp hide_modal(js \\ %JS{}) do
    js
    |> JS.hide(to: "#modal", transition: "fade-out")
    |> JS.hide(to: "#modal-content", transition: "fade-out-scale")
  end
end

lib/stock_exchange_web/live/stock_simulations/receive_stock_simulation.ex
defmodule StockExchangeWeb.Simulation.OutgoingStock do
  @moduledoc """
  This module is for personal test and exploaration, the page joins 'outgoingstock:*' channel 
  and send a stock message that is inputed by a user through a form.
  """
  use StockExchangeWeb, :live_view

  def render(assigns) do
    ~H"""
        <h2> Mobile Notified Stock Information </h2>

        <table>
        <thead>
            <tr>
            <th>Stock Price</th>
            <th>Ticker Symbol</th>
            <th>Category</th>
            <th>Description</th>

            <th></th>
            </tr>
        </thead>
        <tbody id="stock">
            <%= for stock <- @stocks do %>
            <tr id={"stock-#{stock.id}"}>
                <td><%= stock.stock_price %></td>
                <td><%= stock.ticker_symbol %></td>
                <td><%= stock.category %></td>
                <td><%= stock.description%> </td>
                <td> </td>
            </tr>
            <% end %>
        </tbody>
        </table>
    """
  end

  def mount(_params, _session, socket) do
    Phoenix.PubSub.subscribe(StockExchange.PubSub, "outgoingstock:latest")
    {:ok, socket |> assign(:stocks, [])}
  end

  def handle_params(_params, _url, socket) do
    {:noreply, socket}
  end

  def handle_info(%{response: stock}, socket) do
    {:noreply, socket |> assign(:stocks, [stock | socket.assigns.stocks])}
  end
end

lib/stock_exchange_web/live/stock_simulations/send_stock_simulation.ex
defmodule StockExchangeWeb.Simulation.IncomingStock do
  @moduledoc """
  This liveview page subscribes to 'incomingstock:latest' channel and 
  displays messages received.
  """
  use StockExchangeWeb, :live_view

  def render(assigns) do
    ~H"""
    <button id="incoming-channel">Join Channel </button>

        <form phx-submit="submit" phx-change="change" id="incoming-stock">
            <label for="stock_price">Stock Price: </label>
            <input type="number" id="stock-price" name="stock_price"> <br>
            <label for="ticker_symbol">Ticker Symbol: </label>
            <input type="text" id="ticker_symbol" name="ticker_symbol"> <br>
            <label for="market_cap">Market Cap: </label>
            <input type="number" id="market_cap" name="market_cap"> <br>
            <label for="category">Category: </label>
            <input type="text" id="category" name="category"> <br>
            <label for="location">Location: </label>
            <input type="text" id="location" name="location"> <br>
            <button type="submit"> Submit </button> 
        </form>
    """
  end

  def mount(_params, _session, socket) do
    Phoenix.PubSub.subscribe(StockExchange.PubSub, "incomingstock:latest")
    {:ok, socket}
  end

  def handle_params(_params, _url, socket) do
    {:noreply, socket}
  end

  def handle_event("submit", params, socket) do
    broadcast("incomingstock:latest", %{"featured_stock" => params})
    {:noreply, socket}
  end

  def handle_event("change", _params, socket) do
    {:noreply, socket}
  end

  defp broadcast(topic, message) do
    Phoenix.PubSub.broadcast(
      StockExchange.PubSub,
      topic,
      message
    )
  end
end

lib/stock_exchange_web/live/user_live/form_component.ex
defmodule StockExchangeWeb.UserLive.FormComponent do
  use StockExchangeWeb, :live_component

  alias StockExchange.Accounts

  @impl true
  def update(%{user: user} = assigns, socket) do
    changeset = Accounts.change_user(user)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"user" => user_params}, socket) do
    changeset =
      socket.assigns.user
      |> Accounts.change_user(user_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"user" => user_params}, socket) do
    save_user(socket, socket.assigns.action, user_params)
  end

  defp save_user(socket, :edit, user_params) do
    case Accounts.update_user(socket.assigns.user, user_params) do
      {:ok, _user} ->
        {:noreply,
         socket
         |> put_flash(:info, "User updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_user(socket, :new, user_params) do
    case Accounts.create_user(user_params) do
      {:ok, _user} ->
        {:noreply,
         socket
         |> put_flash(:info, "User created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/stock_exchange_web/live/user_live/index.ex
defmodule StockExchangeWeb.UserLive.Index do
  use StockExchangeWeb, :live_view

  alias StockExchange.Accounts
  alias StockExchange.Accounts.User

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :users, list_users())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit User")
    |> assign(:user, Accounts.get_user!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New User")
    |> assign(:user, %User{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Users")
    |> assign(:user, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    user = Accounts.get_user!(id)
    {:ok, _} = Accounts.delete_user(user)

    {:noreply, assign(socket, :users, list_users())}
  end

  defp list_users do
    Accounts.list_users()
  end
end

lib/stock_exchange_web/live/user_live/show.ex
defmodule StockExchangeWeb.UserLive.Show do
  use StockExchangeWeb, :live_view

  alias StockExchange.Accounts

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:user, Accounts.get_user!(id))}
  end

  defp page_title(:show), do: "Show User"
  defp page_title(:edit), do: "Edit User"
end

lib/stock_exchange_web/live/user_live/form_component.html.heex
<div>
  <h2><%= @title %></h2>

  <.form
    let={f}
    for={@changeset}
    id="user-form"
    phx-target={@myself}
    phx-change="validate"
    phx-submit="save">
  
    <%= label f, :name %>
    <%= text_input f, :name %>
    <%= error_tag f, :name %>
  
    <%= label f, :age %>
    <%= number_input f, :age %>
    <%= error_tag f, :age %>

    <%= label f, :email %>
    <%= text_input f, :email %>
    <%= error_tag f, :email %>
  
    <div>
      <%= submit "Save", phx_disable_with: "Saving..." %>
    </div>
  </.form>
</div>

lib/stock_exchange_web/live/user_live/index.html.heex
<h1>Listing Users</h1>

<%= if @live_action in [:new, :edit] do %>
  <.modal return_to={Routes.user_index_path(@socket, :index)}>
    <.live_component
      module={StockExchangeWeb.UserLive.FormComponent}
      id={@user.id || :new}
      title={@page_title}
      action={@live_action}
      user={@user}
      return_to={Routes.user_index_path(@socket, :index)}
    />
  </.modal>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th> Email</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="users">
    <%= for user <- @users do %>
      <tr id={"user-#{user.id}"}>
        <td><%= user.name %></td>
        <td><%= user.age %></td>
        <td><%= user.email %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.user_show_path(@socket, :show, user) %></span>
          <span><%= live_patch "Edit", to: Routes.user_index_path(@socket, :edit, user) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: user.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= live_patch "New User", to: Routes.user_index_path(@socket, :new) %></span>

lib/stock_exchange_web/live/user_live/show.html.heex
<h1>Show User</h1>

<%= if @live_action in [:edit] do %>
  <.modal return_to={Routes.user_show_path(@socket, :show, @user)}>
    <.live_component
      module={StockExchangeWeb.UserLive.FormComponent}
      id={@user.id}
      title={@page_title}
      action={@live_action}
      user={@user}
      return_to={Routes.user_show_path(@socket, :show, @user)}
    />
  </.modal>
<% end %>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @user.name %>
  </li>

  <li>
    <strong>Age:</strong>
    <%= @user.age %>
  </li>

</ul>

<span><%= live_patch "Edit", to: Routes.user_show_path(@socket, :edit, @user), class: "button" %></span> |
<span><%= live_redirect "Back", to: Routes.user_index_path(@socket, :index) %></span>